id: wpconfig-aws-keys1

info:
  name: AWS S3 keys Leak
  author: r12w4n
  severity: high
  tags: aws,s3,wordpress,disclosure


requests:
  - raw:
      - |
        GET /wp-config.php-backup HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept-Encoding: gzip, deflate
        Accept: */*
    matchers:
      - type: word
        words:
          - 'access-key-id'
          - 'secret-access-key'
          - 'DB_NAME'
          - 'DB_PASSWORD'
        condition: and
        part: body
